params:
  alternate: ''
  subtitle: subtitle
  description: this is description
  avatar: avatar.jpg
  since: 2005

  statics: /

  social:
    github:
      icon: ic i-github
      link: https://github.com
    twitter:
      icon: ic i-twitter
      link: https://twitter.com
  favicon:
    apple_touch_icon: /apple-touch-icon.png

  darkmode: true
  auto_scroll: true

  sidebar:
    avatar: avatar.jpg
    position: right

  license:
    name: BY-NC-SA
    url: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh

  fancybox: true
  chart: false
  math: false
  mermaid: false

  loader:
    start: true
    switch: false

  widgets:
    random_posts: false
    recent_comments: false

  algolia:
    vars: ["title", "summary", "path", "content"]
    params: ["tags"]

  vendors:
    css:
      katex: npm/katex@0.12.0/dist/katex.min.css
      comment: css/comment.css
      fancybox: combine/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css,npm/justifiedGallery@3.8.1/dist/css/justifiedGallery.min.css
      waline: npm/@waline/client/dist/waline.css
    js:
      pace: npm/pace-js@1.0.2/pace.min.js
      pjax: npm/pjax@0.2.8/pjax.min.js
      fetch: npm/whatwg-fetch@3.4.0/dist/fetch.umd.min.js
      anime: npm/animejs@3.2.0/lib/anime.min.js
      algolia: npm/algoliasearch@4/dist/algoliasearch-lite.umd.js
      instantsearch: npm/instantsearch.js@4/dist/instantsearch.production.min.js
      lazyload: npm/lozad@1/dist/lozad.min.js
      quicklink: npm/quicklink@2/dist/quicklink.umd.js
      fancybox: combine/npm/jquery@3.5.1/dist/jquery.min.js,npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js,npm/justifiedGallery@3.8.1/dist/js/jquery.justifiedGallery.min.js
      valine: gh/amehime/MiniValine@4.2.2-beta10/dist/MiniValine.min.js
      copy_tex: npm/katex@0.12.0/dist/contrib/copy-tex.min.js
      chart: npm/frappe-charts@1.5.0/dist/frappe-charts.min.iife.min.js
      waline: npm/@waline/client/dist/waline.js
